version: "3.8"

services:
    web:
        container_name: nextjs_app
        build: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        volumes:
            - .:/app
            - /app/node_modules
        restart: unless-stopped
