import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/Header";

// Thêm kiểu chữ Helvetica Neue
const customFont = {
    variable: "--font-custom",
    subsets: ["latin"],
};
const header = <Header />;
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${customFont.variable} antialiased`}
                style={{ fontFamily: "Helvetica Neue, Arial, sans-serif" }}
            >
                {header}
                {children}
            </body>
        </html>
    );
}
