import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "@/components/layout/Footer";
import Script from "next/script";

// Thêm kiểu chữ Helvetica Neue
const customFont = {
    variable: "--font-custom",
    subsets: ["latin"],
};
const header = <Header />;
const footer = <Footer />;
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                // id="fb-root"
                className={`${customFont.variable} antialiased`}
                style={{ fontFamily: "Helvetica Neue, Arial, sans-serif" }}
            >
                <Script
                    src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v22.0"
                    strategy="lazyOnload"
                    crossOrigin="anonymous"
                />
                {header}
                {children}
                {footer}
            </body>
        </html>
    );
}
